# **1. Các bài toán cơ bản về không gian vector**

Bài toán 1

In [ ]:
#a. x = 2u − (v + 3w)
import numpy as np
u = np.array([2,-1,5,0])
v = np.array([4,3,1,-1])
w = np.array([-6,2,0,3])
x = 2*u-(v+3*w)
print(x)

[ 18 -11   9  -8]


In [ ]:
#b. 3(x + w) = 2u − v + x
x = 0.5*(2*u-v-3*w)
print (x)

[ 9.  -5.5  4.5 -4. ]


Bài toán 2

In [ ]:
from numpy import linalg
A = np.matrix([[0, -1, 3],[1, 1, 1],[4, 2, 2]])
B = np.array([-1, -2, -2])
X = np.linalg.solve(A, B)
print (X)

[ 1. -2. -1.]


Bài toán 3

In [ ]:
A = np.matrix([[1,0],[0,0]])
B = np.matrix([[0,0],[0,1]])
from numpy import linalg as LA
#Phương pháp 1
LA.inv(A) #LinAlgError
LA.inv(B) #LinAlgError
LA.inv(A+B)

matrix([[1., 0.],
        [0., 1.]])

In [ ]:
#Phương pháp 2
LA.det(A)
LA.det(B)
LA.det(A+B)

np.float64(1.0)

Bài toán 4

In [ ]:
import sympy as sp
x, y = sp.symbols('x y') # khai báo 2 biến x và y
A = sp.Matrix([[x, y],[y, x]]) # lưu ý: kiểu ma trận của sympy là ‘Matrix’ (viết hoa)
x1, y1 = sp.symbols('x1 y1')
A1 = sp.Matrix([[x1, y1],[y1, x1]])
x2, y2 = sp.symbols('x2 y2')
A2 = sp.Matrix([[x2, y2],[y2, x2]])
A1.T

Matrix([
[x1, y1],
[y1, x1]])

In [ ]:
(A1+A2).T

Matrix([
[x1 + x2, y1 + y2],
[y1 + y2, x1 + x2]])

In [ ]:
((A1+A2).T).equals(A1+A2)

True

In [ ]:
c = sp.symbols('c')
c*A

Matrix([
[c*x, c*y],
[c*y, c*x]])

In [ ]:
((c*A).T).equals(c*A)

True

Bài toán 5

In [ ]:
import numpy as np
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
v3 = np.array([7, 8, 9])

#a. Vector w = (1,1,1) là tổ hợp tuyến tính của 3 vector trên.
w1 = np.array([1,1,1])

# Câu b: Kiểm tra w = (1, -2, 2)
w2 = np.array([1, -2, 2])

# Hàm kiểm tra tổ hợp tuyến tính
def check_linear_combination(A, w):
    try:
        c = np.linalg.solve(A, w)
        print(f"Vector {w} LÀ tổ hợp tuyến tính. Hệ số: {c}")
    except np.linalg.LinAlgError:
        print(f"Vector {w} KHÔNG là tổ hợp tuyến tính.")

# Thực hiện kiểm tra
print("Câu a:")
check_linear_combination(A, w1)

print("\nCâu b:")
check_linear_combination(A, w2)

Câu a:
Vector [1 1 1] LÀ tổ hợp tuyến tính. Hệ số: [ 5.00000000e-01 -1.66533454e-16 -5.00000000e-01]

Câu b:
Vector [ 1 -2  2] LÀ tổ hợp tuyến tính. Hệ số: [ 3.15251974e+16 -6.30503948e+16  3.15251974e+16]


Bài toán 6

In [ ]:
import sympy as sp
c1, c2, c3 = sp.symbols('c1 c2 c3')
sp.solve([c1-2*c3, 2*c1+c2, 3*c1+2*c2+c3], [c1, c2, c3])

{c1: 0, c2: 0, c3: 0}

Bài toán 7

In [ ]:
import sympy as sp
c1, c2 = sp.symbols('c1 c2')
u1, u2 = sp.symbols('u1 u2')
sp.solve([c1+c2-u1,c1-c2-u2])
u1 = 2
u2 = 5
sp.solve([c1+c2-u1,c1-c2-u2])

{c1: 7/2, c2: -3/2}

# **2. Ánh xạ tuyến tính**


2.2.Bài toán ứng dụng: Ma trận biến đổi (ảnh/font chữ/…)

a. Biến đổi tịnh tiến.

In [ ]:
import numpy as np
P = np.array([[0,0,3,3,1,1,2,2,1,1],[0,5,5,4,4,3,3,2,2,0]])
vecdelta = np.array([4,2])
P_caua = (P.T + vecdelta).T
print (P_caua)

[[4 4 7 7 5 5 6 6 5 5]
 [2 7 7 6 6 5 5 4 4 2]]


b. Biến đổi tịnh tiến và co giãn.

In [ ]:
himport numpy as np
P = np.array([[0,0,3,3,1,1,2,2,1,1],[0,5,5,4,4,3,3,2,2,0]])
vecdelta = np.array([4,-2])
matran_biendoi = np.array([[1.0, 0.0],
                            [0.0, 2.0]])
P_caub = (P.T @ matran_biendoi + vecdelta).T
print (P_caub)

[[ 4.  4.  7.  7.  5.  5.  6.  6.  5.  5.]
 [-2.  8.  8.  6.  6.  4.  4.  2.  2. -2.]]


# **BÀI TẬP CHƯƠNG**

In [3]:
from sympy import symbols, Matrix, simplify
x, y, z, a, b, c = symbols('x y z a b c')
def g(v):
    x, y, z = v
    return Matrix([x + y, z + 2, 0])
u = Matrix([x, y, z])
v = Matrix([a, b, c])
left1 = g(u + v)
right1 = g(u) + g(v)

left2 = g(2 * u)
right2 = 2 * g(u)
print("g(u + v) == g(u) + g(v):", simplify(left1 - right1) == Matrix([0,0,0]))
print("g(c * u) == c * g(u):", simplify(left2 - right2) == Matrix([0,0,0]))

g(u + v) == g(u) + g(v): False
g(c * u) == c * g(u): False


In [4]:
from sympy import Matrix
A = Matrix([[0, 1],
            [1, -1]])
F = [
    Matrix([0, 0]),
    Matrix([1, 0]),
    Matrix([1, 1]),
    Matrix([0, 1])
]
transformed_F = [A * point for point in F]
print("Tọa độ sau khi biến đổi:")
for i, point in enumerate(transformed_F):
    print(f"f(F[{i}]) = {point}")


Tọa độ sau khi biến đổi:
f(F[0]) = Matrix([[0], [0]])
f(F[1]) = Matrix([[0], [1]])
f(F[2]) = Matrix([[1], [0]])
f(F[3]) = Matrix([[1], [-1]])


In [5]:
from sympy import Matrix, symbols, simplify
v1, v2, u1, u2, c = symbols('v1 v2 u1 u2 c')
def T(v):
    return Matrix([v[0] - v[1], v[0] + 2*v[1]])
u = Matrix([u1, u2])
v = Matrix([v1, v2])
left1 = T(u + v)
right1 = T(u) + T(v)
left2 = T(c * u)
right2 = c * T(u)
print("T(u + v) == T(u) + T(v):", simplify(left1 - right1) == Matrix([0, 0]))
print("T(c * u) == c * T(u):", simplify(left2 - right2) == Matrix([0, 0]))

T(u + v) == T(u) + T(v): True
T(c * u) == c * T(u): True


In [7]:
from sympy import *
import numpy as np
x, y = symbols('x y')
X = Matrix([x, y])
A = Matrix([[13, -5], [-5, 13]])
eigenvals = A.eigenvals()
eigenvects = A.eigenvects()
print("Giá trị riêng:", eigenvals)
P, D = A.diagonalize(normalize=True)
print("Ma trận P (trực giao):")
pprint(P)
print("Ma trận D (chéo):")
pprint(D)
possible_angles = [pi/4, 3*pi/4, 7*pi/4]
for angle in possible_angles:
    P_test = Matrix([[cos(angle), -sin(angle)],
                     [sin(angle), cos(angle)]])
    D_test = P_test.T * A * P_test
    print(f"\nKiểm tra góc {angle*180/pi.evalf()}°:")
    pprint(D_test)

Giá trị riêng: {18: 1, 8: 1}
Ma trận P (trực giao):
⎡√2  -√2 ⎤
⎢──  ────⎥
⎢2    2  ⎥
⎢        ⎥
⎢√2   √2 ⎥
⎢──   ── ⎥
⎣2    2  ⎦
Ma trận D (chéo):
⎡8  0 ⎤
⎢     ⎥
⎣0  18⎦

Kiểm tra góc 14.3239448782706*pi°:
⎡8  0 ⎤
⎢     ⎥
⎣0  18⎦

Kiểm tra góc 42.9718346348117*pi°:
⎡18  0⎤
⎢     ⎥
⎣0   8⎦

Kiểm tra góc 100.267614147894*pi°:
⎡18  0⎤
⎢     ⎥
⎣0   8⎦
