# **Bài 1**

# **1.1**

In [6]:
import numpy as np
D = np.array([[1,2],[3,4]])
np.copyto(E, D)
E = np.array([[1,2],[3,5]])
np.copyto(E, D)
print(E)

[[1 2]
 [3 4]]


# **1.2**

In [8]:
x = np.array([['a','b'],['c','d']])
y = 'x'
C = np.matrix([[x, y], [1, 2]], dtype=object)
print (C)

[[array([['a', 'b'],
         ['c', 'd']], dtype='<U1') 'x']
 [1 2]]


In [9]:
A = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(A)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# **1.3**

In [10]:
from numpy import matlib
G = matlib.identity(5)
print (G)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [11]:
H = matlib.randn(3,2)
print(H)

[[-0.41450256  0.45439079]
 [-0.1770996   1.03431684]
 [-0.69427564  0.13186718]]


In [12]:
K = matlib.zeros([4,4])
print(K)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# **Bài 2**

# **2.2**

In [15]:
import numpy as np
c = [3, 7, 15, 1, 292, 1, 1, 1, 2, 1, 3, 1, 14, 2]
M = np.asmatrix([[1,2],[3,4]])
for i in range(len(c)):
  ci = np.asmatrix([[1,1],[1,0]])
  ci[0, 0] = c[i]
  if (i==0):
    M = ci
  else:
    M = M.dot(ci)
print(M)
print (M[0,0]/M[1,0])

[[165707065  80143857]
 [ 52746197  25510582]]
3.1415926535897936


In [16]:
X = np.array([[1, 1], [1, 2], [1, 3], [1, 4], [1, 5]])
Y = np.array([[2], [4], [4], [4], [6]])
XT = X.T
A1 = np.linalg.inv(XT.dot(X))  # (X^T X)^(-1)
A2 = XT.dot(Y)                 # X^T Y
A = A1.dot(A2)
f = X.dot(A)  # f_i = a0 + a1*x_i
error = f - Y
total_squared_error = (error.T).dot(error)
print(f"Hệ số hồi quy: a0 = {A[0][0]:.2f}, a1 = {A[1][0]:.2f}")
print(f"Phương trình: y = {A[0][0]:.2f} + {A[1][0]:.2f}x")
print(f"Tổng bình phương sai số: {total_squared_error[0][0]:.2f}")

Hệ số hồi quy: a0 = 1.60, a1 = 0.80
Phương trình: y = 1.60 + 0.80x
Tổng bình phương sai số: 1.60


# **Bài tập chương**

# **Bài 1**

In [17]:
import numpy as np

# Tạo ma trận X (thêm cột số 1 để tính hệ số chệch a0)
X = np.array([[1, 0],
              [1, 1],
              [1, 2],
              [1, 3],
              [1, 4]])

# Tạo vector Y
Y = np.array([[10],
              [8],
              [7],
              [5],
              [2]])
# Tính X^T
XT = X.T

# Tính A1 = (X^T X)^(-1)
A1 = np.linalg.inv(XT.dot(X))

# Tính A2 = X^T Y
A2 = XT.dot(Y)

# Tính A = A1 . A2
A = A1.dot(A2)
# Lấy hệ số a0 và a1
a0 = A[0][0]
a1 = A[1][0]

# In phương trình hồi quy
print(f"Phương trình hồi quy gần đúng: y = {a0:.2f} + {a1:.2f}x")

# Tính các giá trị dự đoán f_i và sai số bình phương
f = X.dot(A)
error = f - Y
squared_error = (error.T).dot(error)

# In tổng sai số bình phương
print(f"Tổng bình phương sai số: {squared_error[0][0]:.2f}")


Phương trình hồi quy gần đúng: y = 10.20 + -1.90x
Tổng bình phương sai số: 1.10


In [24]:
import numpy as np

def bpcuctieu(y):  # y là list [10, 8, 7, 5, 2]
    x = np.array([[1, 0],
                  [1, 1],
                  [1, 2],
                  [1, 3],
                  [1, 4]])  # đúng thứ tự x: 0,1,2,3,4

    y = np.array(y).reshape(-1, 1)

    # Tính A = (X^T X)^(-1) X^T Y
    XT = x.T
    A1 = np.linalg.inv(XT.dot(x))
    A2 = XT.dot(y)
    A = A1.dot(A2)

    print(f"Phương trình gần đúng: y = {A[0][0]:.1f} + ({A[1][0]:.1f})x")
    return A

dulieu = [10.0, 8, 7, 5, 2]
bpcuctieu(dulieu)

Phương trình gần đúng: y = 10.2 + (-1.9)x


array([[10.2],
       [-1.9]])