#**Bài 1**

In [ ]:
#Bài 1
#Hàm “scale” tỉ số vector bằng một giá trị thực
def scale(a, v):
  return [a*vi for vi in v]
v = [3,5,7]
print('Hàm “scale” tỉ số vector bằng một giá trị thực',scale(10, v))
#Hàm lấy tổng hai vector
def sumvector(v, w):
  return [vi+wi for (vi, wi) in zip(v, w)]
v = [3,5,7]
w = [2,4,6]
print('Hàm lấy tổng hai vector',sumvector(v, w))
#Hàm nhân 2 vector vô hướng
def dotvector(v, w):
  return sum([vi*wi for (vi, wi) in zip(v, w)])
print('Hàm nhân 2 vector vô hướng',dotvector(v, w))
#Hàm tính chiều dài một vector
def lenvector(v):
  return dotvector(v,v)
print('Hàm tính chiều dài một vector',lenvector(w))

[30, 50, 70]
[5, 9, 13]
68


# Bài **2**

In [ ]:
#Bài 2
import numpy as np
scores = np.array([-1, 1, 2, -3, 5, -4])
print(scores >= 0)
print(scores < 0)
print(np.select([scores >=0, scores < 0],['so duong', 'so am'], default=''))
scores = np.array([-1, 1, 2, 0, -3, 5, 0, -4])
print(np.select([scores >0, scores ==0, scores < 0],['so duong', 'so 0', 'so am'],default = ''))

[False  True  True False  True False]
[ True False False  True False  True]
['so am' 'so duong' 'so duong' 'so am' 'so duong' 'so am']
['so am' 'so duong' 'so duong' 'so 0' 'so am' 'so duong' 'so 0' 'so am']


# Bài **3.1**

In [ ]:
#1
import numpy as np
from scipy import linalg, sparse

In [ ]:
#2
D = np.asmatrix([ [3,4], [5,6] ])
print(D)

[[3 4]
 [5 6]]


In [ ]:
#3
C = np.asmatrix(np.random.random((5,7)))
print(C)

[[0.86758927 0.73202414 0.98980522 0.81513607 0.03351877 0.11137775
  0.192663  ]
 [0.71378298 0.90333743 0.35810448 0.65432906 0.88753253 0.69478204
  0.2323389 ]
 [0.77180995 0.10416448 0.65782333 0.98934805 0.63995849 0.4445396
  0.02321745]
 [0.54029414 0.71399214 0.45205811 0.14570945 0.6768957  0.57877612
  0.37227087]
 [0.0608277  0.57943216 0.27025149 0.32998224 0.73239292 0.31082831
  0.31154853]]


In [ ]:
#4
A = np.asmatrix(np.random.random((2,2)))
print(A)

[[0.15879819 0.3176143 ]
 [0.257993   0.71515599]]


In [ ]:
#5
b = np.array([(1+5j, 2j, 3j),(4, 5, 6)])
B = np.asmatrix(b)
print(b)
print(B)

[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]
[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]


In [ ]:
#6
print(A.T)
print(A.I)

[[0.52484504 0.14320318]
 [0.68457388 0.60016164]]
[[ 2.76624827 -3.15531879]
 [-0.66004811  2.41910112]]


In [ ]:
#7
print(linalg.inv(A))
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]])
print(M)

[[ 2.76624827 -3.15531879]
 [-0.66004811  2.41910112]]
[[-1  3  2]
 [ 0 -2  1]
 [ 1  5 -2]]


In [ ]:
#8
M_lower = np.tril(M)
print(M_lower)

[[-1  0  0]
 [ 0 -2  0]
 [ 1  5 -2]]


In [ ]:
#9
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]])
M_upper = np.triu(M)
print(M_upper)

[[-1  3  2]
 [ 0 -2  1]
 [ 0  0 -2]]


In [ ]:
#10
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]])
v_diag = np.diag(M)
print (v_diag)
M_diag = np.diag(v_diag)

[-1 -2 -2]


# Bài **3.2**

In [ ]:
import numpy as np
A = np.reshape(np.arange(36.0), (6,6))
print(A)
I6 = np.identity(6)
print(I6)
vecB = np.array([1., 2., 3., 4., 5., 6.])
C = A.dot(vecB)
print(C)
D = np.array([[1., 2., 3., 4., 5., 6.], [1., 0., 1., 0., 1., 0.]])
print(D)
E = A.dot(D.T)
print(E)
F = np.array([[1., 1.], [2., 0.], [3., 1.], [4., 0], [5., 1], [6., 0.]])
G = A.dot(F)
print(F)
print(G)
K = np.identity(6)
H = np.linalg.inv(K)
J = np.linalg.inv(np.linalg.inv(K))
print(H)
print(J)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[ 70. 196. 322. 448. 574. 700.]
[[1. 2. 3. 4. 5. 6.]
 [1. 0. 1. 0. 1. 0.]]
[[ 70.   6.]
 [196.  24.]
 [322.  42.]
 [448.  60.]
 [574.  78.]
 [700.  96.]]
[[1. 1.]
 [2. 0.]
 [3. 1.]
 [4. 0.]
 [5. 1.]
 [6. 0.]]
[[ 70.   6.]
 [196.  24.]
 [322.  42.]
 [448.  60.]
 [574.  78.]
 [700.  96.]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


# **Bài 4**

In [ ]:
import numpy as np
A = np.array( [ [1,1], [1,0] ] )
b = np.array([1, 0])
n = 1014
for i in range(n):
  b = A.dot(b)
  print(b)

[1 1]
[2 1]
[3 2]
[5 3]
[8 5]
[13  8]
[21 13]
[34 21]
[55 34]
[89 55]
[144  89]
[233 144]
[377 233]
[610 377]
[987 610]
[1597  987]
[2584 1597]
[4181 2584]
[6765 4181]
[10946  6765]
[17711 10946]
[28657 17711]
[46368 28657]
[75025 46368]
[121393  75025]
[196418 121393]
[317811 196418]
[514229 317811]
[832040 514229]
[1346269  832040]
[2178309 1346269]
[3524578 2178309]
[5702887 3524578]
[9227465 5702887]
[14930352  9227465]
[24157817 14930352]
[39088169 24157817]
[63245986 39088169]
[102334155  63245986]
[165580141 102334155]
[267914296 165580141]
[433494437 267914296]
[701408733 433494437]
[1134903170  701408733]
[1836311903 1134903170]
[2971215073 1836311903]
[4807526976 2971215073]
[7778742049 4807526976]
[12586269025  7778742049]
[20365011074 12586269025]
[32951280099 20365011074]
[53316291173 32951280099]
[86267571272 53316291173]
[139583862445  86267571272]
[225851433717 139583862445]
[365435296162 225851433717]
[591286729879 365435296162]
[956722026041 591286729879]
[15480087559

# Bài **5**

In [ ]:
import sympy as sp
from sympy import Symbol
x1 = Symbol('x1')
x2 = Symbol('x2')
x3 = Symbol('x3')
x4 = Symbol('x4')
from sympy import solve
pt1 = x4+610-450-x1
pt2 = x1+400-x2-640
pt3 = x2+600-x3
pt4 = x3-x4-520
nghiem = sp.solve((pt1, pt2, pt3, pt4))
print(nghiem)

{x1: x4 + 160, x2: x4 - 80, x3: x4 + 520}


# **Bài** **tập**

# **Câu 1**

In [ ]:
#Problem 1: Giao điểm hai đường thẳng trong R^2
import numpy as np
a1 = np.array([[1, -1],
               [2, 3]])
b1 = np.array([-2, 6])
x1 = np.linalg.solve(a1, b1)
print("Kết quả của Problem 1 (x, y):", x1)

Kết quả của Problem 1 (x, y): [0. 2.]


In [ ]:
# Problem 2: Giao điểm ba mặt phẳng trong R^3
a2 = np.array([[1, -1, 0],
               [2, -1, -1],
               [1, 1, 1]])
b2 = np.array([2, 3, 6])
x2 = np.linalg.solve(a2, b2)
print("Kết quả của Problem 2 (x, y):", x2)

Kết quả của Problem 2 (x, y): [3. 1. 2.]


In [ ]:
# Problem 3: Tìm hệ số đa thức bậc hai p(x) = ax^2 + bx + c
a3 = np.array([[1, 1, 1],
               [4, 2, 1],
               [9, 3, 1]])
b3 = np.array([4, 3, 4])
x3 = np.linalg.solve(a3, b3)
print("Kết quả của Problem 3 (x, y):", x3)

Kết quả của Problem 3 (x, y): [ 1. -4.  7.]


In [ ]:
# Problem 4: Phân rã thành phân số đơn giản để tính tích phân
a4 = np.array([[1, 0, 1],
               [1, 1, -2],
               [-2, 2, 1]])
b4 = np.array([1, -3, 0])
x4 = np.linalg.solve(a4, b4)
print("Kết quả của Problem 4 (x, y):", x4)

Kết quả của Problem 4 (x, y): [-0.11111111 -0.66666667  1.11111111]


# **Câu 2**

In [ ]:
# Import, khởi tạo biến
from sympy import symbols, Eq, solve, Matrix
x, y, z = symbols('x y z')
a, b, c = symbols('a b c')

In [ ]:
#Problem 1: Giao điểm hai đường thẳng trong R^2
eq1 = Eq(x - y, -2)
eq2 = Eq(2*x + 3*y, 6)
sol1 = solve((eq1, eq2), (x, y))
print('Problem 1: ', sol1)

Problem 1:  {x: 0, y: 2}


In [ ]:
#Problem 2: Giao điểm ba mặt phẳng trong R^3
eq3 = Eq(x - y, 2)
eq4 = Eq(2*x - y - z, 3)
eq5 = Eq(x + y + z, 6)
sol2 = solve((eq3, eq4, eq5), (x, y, z))
print('Problem 2: ', sol2)

Problem 2:  {x: 3, y: 1, z: 2}


In [ ]:
# Problem 3: Tìm hệ số đa thức bậc hai p(x) = ax^2 + bx + c
# p(1) = 4, p(2) = 3, p(3) = 4
# p(1) = 4:
eq6 = Eq(a + b + c, 4)
# p(2) = 3:
eq7 = Eq(4*a + 2*b + c, 3)
# p(3) = 4:
eq8 = Eq(9*a + 3*b + c, 4)
sol3 = solve((eq6, eq7, eq8), (a, b, c))
print('Problem 3: ', sol3)

Problem 3:  {a: 1, b: -4, c: 7}


In [ ]:
# Problem 4: Phân rã thành phân số đơn giản để tính tích phân
eq9  = Eq(a + c, 1)
eq10 = Eq(a + b - 2*c, -3)
eq11 = Eq(-2*a + 2*b + c, 0)
sol4 = solve((eq9, eq10, eq11), (a, b, c))
print('problem 4: ', sol4)

problem 4:  {a: -1/9, b: -2/3, c: 10/9}


# **Câu 3**

In [1]:
# SymPy
from sympy import Matrix,symbols,simplify
k=symbols('k',integer=True,positive=True)
F=Matrix([[1,1],[1,0]])
F_k=F**k
print("Dạng tổng quát của F^k:")
display(F_k)

#NumPy
import numpy as np
def fibonacci_matrix(k):
    F=np.array([[1,1],[1,0]])
    return np.linalg.matrix_power(F,k)
k=5
F_5=fibonacci_matrix(k)
print(f"\nMa trận F^{k}:")
print(F_5)

Dạng tổng quát của F^k:


Matrix([
[-(-5 + sqrt(5))*(1/2 - sqrt(5)/2)**k/((-5 + 5*sqrt(5))*(1/2 + sqrt(5)/2)) - sqrt(5)*(1/2 + sqrt(5)/2)**k/(5*(1/2 - sqrt(5)/2)), -(1/2 - sqrt(5)/2)**k*(sqrt(5)/10 + 1/2)/(1/2 + sqrt(5)/2) - 2*sqrt(5)*(1/2 + sqrt(5)/2)**k/((1/2 - sqrt(5)/2)*(5 + 5*sqrt(5)))],
[                                         (-5 + sqrt(5))*(1/2 - sqrt(5)/2)**k/(-5 + 5*sqrt(5)) + sqrt(5)*(1/2 + sqrt(5)/2)**k/5,                                        (1/2 - sqrt(5)/2)**k*(sqrt(5)/10 + 1/2) + 2*sqrt(5)*(1/2 + sqrt(5)/2)**k/(5 + 5*sqrt(5))]])


Ma trận F^5:
[[8 5]
 [5 3]]
