# **Câu 1**

In [3]:
from scipy import linalg
import numpy as np
a = np.array([1, 2, 3])
b = np.array([(1+9j, 2j, 3j), (4j, 5j, 6j)])
c = np.array([[ (0.5, 1.5, 10), (3,2,1) ] , [(6,5,4), (7,8,9)]])
A = np.matrix(np.random.random( (2,2) ) )
B = np.asmatrix(b)
C = np.asmatrix(np.random.random( (10,5) ) )
D = np.asmatrix([ [4, 3], [2, 6] ])
F = np.eye(3, k=1)
print(A)
print(B)
print(C)
print(D)
print(F)

[[0.08768658 0.85389179]
 [0.17440832 0.89708995]]
[[1.+9.j 0.+2.j 0.+3.j]
 [0.+4.j 0.+5.j 0.+6.j]]
[[0.60008778 0.69708346 0.59792896 0.9814703  0.81626453]
 [0.61951563 0.61026373 0.59760136 0.90467978 0.48999198]
 [0.48047881 0.18958441 0.55686788 0.12355531 0.45074688]
 [0.68547604 0.42730315 0.85917049 0.57825634 0.29294447]
 [0.01635153 0.36363414 0.36796278 0.83092693 0.80189613]
 [0.87611558 0.01443622 0.36191822 0.84085976 0.60115278]
 [0.0469573  0.78439053 0.09254484 0.53408766 0.35825659]
 [0.09229271 0.60205846 0.70113567 0.21098938 0.8917945 ]
 [0.66904666 0.77699982 0.46057509 0.05039395 0.01935813]
 [0.49809907 0.27505605 0.37708976 0.25953115 0.70257396]]
[[4 3]
 [2 6]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [4]:
F = np.eye(3, k=0)
print(F)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
F = np.eye(3, k=-1)
print(F)

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [6]:
#Xem hạng ma trận
print('Hạng của ma trận',np.linalg.matrix_rank(C))

5


In [7]:
#Ma trận nghịch đảo
print(A.I)

[[-12.76758553  12.15277967]
 [  2.48221835  -1.24797505]]


In [8]:
#Lệnh của gói Scipy
print(linalg.inv(A))

[[-12.76758553  12.15277967]
 [  2.48221835  -1.24797505]]


In [9]:
#Định thức ma trận
print(linalg.det(A))

-0.0702630848375403


In [11]:
#Chuyển đổi ma trận(chuyển vị)
A.T

matrix([[0.08768658, 0.17440832],
        [0.85389179, 0.89708995]])

In [12]:
#Chuyển vị liên hợp
A.H

matrix([[0.08768658, 0.17440832],
        [0.85389179, 0.89708995]])

In [13]:
linalg.solve(A, b)

array([[-12.76758553-6.62971511e+01j,   0.        +3.52287273e+01j,
          0.        +3.46139214e+01j],
       [  2.48221835+1.73480650e+01j,   0.        -1.27543854e+00j,
          0.        -4.11952338e-02j]])

In [16]:
E = np.asmatrix(a).T
print(E)

[[1]
 [2]
 [3]]


In [17]:
linalg.lstsq(F, E)

(array([[2.],
        [3.],
        [0.]]),
 array([], dtype=float64),
 2,
 array([1., 1., 0.]))

In [18]:
#Cộng ma trận
np.add(A, D)

matrix([[4.08768658, 3.85389179],
        [2.17440832, 6.89708995]])

In [19]:
#Trừ ma trận
np.subtract(A, D)

matrix([[-3.91231342, -2.14610821],
        [-1.82559168, -5.10291005]])

In [20]:
#Chia ma trận
np.divide(A, D)

matrix([[0.02192164, 0.2846306 ],
        [0.08720416, 0.14951499]])

In [25]:
#Nhân ma trận
A @ D #Phiên bản Py 3.x
np.multiply(D, A)
np.dot(D, A)

matrix([[0.87397126, 6.10683699],
        [1.22182306, 7.09032325]])

In [27]:
#Hàm lũy thừa ma trận
linalg.expm(A)
#Hàm logarith ma trận
linalg.logm(A)

array([[-2.32507026+2.70759747j,  2.10426564-2.39856961j],
       [ 0.42979853-0.48991043j, -0.33043847+0.43399519j]])

# **Câu 2**

In [31]:
import numpy as np
#Tính ma trận A
A = np.array([ [0,1], [1,0]])
print(A)
temp = A.dot(A) # tính toan lần thứ 1
print(temp)
k = 6
for i in range(k-1):
  temp = temp.dot(A)
print (temp)
print('---')
#Tính ma trận B
B = np.array([ [0,-1], [-1,0]])
print(B)
temp = B.dot(B) # tính toan lần thứ 1
print(temp)
k= 5
for i in range(k-1):
  temp = temp.dot(B)
print (temp)
print('---')
#Ma trận hội tụ
C = np.array([ [1, 0, 0], [0, 0.5, 1], [0, 0, 0.5] ])
print(C)
temp = C.dot(C) # tính toan lần thứ 1
print(temp)
k= 1000
for i in range(k-1):
  temp = temp.dot(C)
print(temp)
k= 1000
for i in range(k-1):
  temp = temp.dot(C)
print(temp)

[[0 1]
 [1 0]]
[[1 0]
 [0 1]]
[[0 1]
 [1 0]]
---
[[ 0 -1]
 [-1  0]]
[[1 0]
 [0 1]]
[[1 0]
 [0 1]]
---
[[1.  0.  0. ]
 [0.  0.5 1. ]
 [0.  0.  0.5]]
[[1.   0.   0.  ]
 [0.   0.25 1.  ]
 [0.   0.   0.25]]
[[1.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 4.66631809e-302 9.34196882e-299]
 [0.00000000e+000 0.00000000e+000 4.66631809e-302]]
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [36]:
#Ma trận Markov
M = np.array([ [0.8, 0.3], [0.2, 0.7]])
MM = M.dot(M) # tính M2, nghĩa là M2
print (MM)
MMM = M.dot(MM) # tính M3
print (MMM)
for i in range(100): # tính các M^ khác.
  MM = MM.dot(M)
print (MM) # kết luận xu hướng của M mũ vô hạn

[[0.7  0.45]
 [0.3  0.55]]
[[0.65  0.525]
 [0.35  0.475]]
[[0.6 0.6]
 [0.4 0.4]]


# **Câu 3**

In [37]:
#Phân rã ma trận LU
M = np.array([ [0.8, 0.3], [0.2, 0.7]])
P, L, U = linalg.lu(M) # lệnh lina.lu sẽ tách ma trận M thành 3 ma trận P, L và U
print (P)
print (L)
print (U)
L.dot(U)

[[1. 0.]
 [0. 1.]]
[[1.   0.  ]
 [0.25 1.  ]]
[[0.8   0.3  ]
 [0.    0.625]]


array([[0.8, 0.3],
       [0.2, 0.7]])

# **Câu 5**

In [38]:
#Bài toán loan tin
A = np.array([ [0,1,0,1],[0,0,1,0],[1,0,0,1],[1,1,0,0]])
temp = A.dot(A) # lúc này temp =› A^2
print(temp)
temp = temp.dot(A) # lúc này temp =› A^3
print(temp)

[[1 1 1 0]
 [1 0 0 1]
 [1 2 0 1]
 [0 1 1 1]]
[[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]


In [40]:
A = np.array([ [0,1,0,1],[0,0,1,0],[1,0,0,1],[1,1,0,0]])
sumA = A
temp = A.dot(A)
k = 3
sumA = sumA + temp
for i in range(1, k-1):
  temp = temp.dot(A)
sumA = sumA + temp
print (temp)
print('---')
print (sumA)

[[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]
---
[[2 3 2 3]
 [2 2 1 2]
 [3 4 2 3]
 [3 3 2 2]]
