# **Câu 1**

In [ ]:
from scipy import linalg
import numpy as np
a = np.array([1, 2, 3])
b = np.array([(1+9j, 2j, 3j), (4j, 5j, 6j)])
c = np.array([[ (0.5, 1.5, 10), (3,2,1) ] , [(6,5,4), (7,8,9)]])
A = np.matrix(np.random.random( (2,2) ) )
B = np.asmatrix(b)
C = np.asmatrix(np.random.random( (10,5) ) )
D = np.asmatrix([ [4, 3], [2, 6] ])
F = np.eye(3, k=1)
print(A)
print(B)
print(C)
print(D)
print(F)

[[0.08768658 0.85389179]
 [0.17440832 0.89708995]]
[[1.+9.j 0.+2.j 0.+3.j]
 [0.+4.j 0.+5.j 0.+6.j]]
[[0.60008778 0.69708346 0.59792896 0.9814703  0.81626453]
 [0.61951563 0.61026373 0.59760136 0.90467978 0.48999198]
 [0.48047881 0.18958441 0.55686788 0.12355531 0.45074688]
 [0.68547604 0.42730315 0.85917049 0.57825634 0.29294447]
 [0.01635153 0.36363414 0.36796278 0.83092693 0.80189613]
 [0.87611558 0.01443622 0.36191822 0.84085976 0.60115278]
 [0.0469573  0.78439053 0.09254484 0.53408766 0.35825659]
 [0.09229271 0.60205846 0.70113567 0.21098938 0.8917945 ]
 [0.66904666 0.77699982 0.46057509 0.05039395 0.01935813]
 [0.49809907 0.27505605 0.37708976 0.25953115 0.70257396]]
[[4 3]
 [2 6]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [ ]:
F = np.eye(3, k=0)
print(F)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
F = np.eye(3, k=-1)
print(F)

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [ ]:
#Xem hạng ma trận
print('Hạng của ma trận',np.linalg.matrix_rank(C))

5


In [ ]:
#Ma trận nghịch đảo
print(A.I)

[[-12.76758553  12.15277967]
 [  2.48221835  -1.24797505]]


In [ ]:
#Lệnh của gói Scipy
print(linalg.inv(A))

[[-12.76758553  12.15277967]
 [  2.48221835  -1.24797505]]


In [ ]:
#Định thức ma trận
print(linalg.det(A))

-0.0702630848375403


In [ ]:
#Chuyển đổi ma trận(chuyển vị)
A.T

matrix([[0.08768658, 0.17440832],
        [0.85389179, 0.89708995]])

In [ ]:
#Chuyển vị liên hợp
A.H

matrix([[0.08768658, 0.17440832],
        [0.85389179, 0.89708995]])

In [ ]:
linalg.solve(A, b)

array([[-12.76758553-6.62971511e+01j,   0.        +3.52287273e+01j,
          0.        +3.46139214e+01j],
       [  2.48221835+1.73480650e+01j,   0.        -1.27543854e+00j,
          0.        -4.11952338e-02j]])

In [ ]:
E = np.asmatrix(a).T
print(E)

[[1]
 [2]
 [3]]


In [ ]:
linalg.lstsq(F, E)

(array([[2.],
        [3.],
        [0.]]),
 array([], dtype=float64),
 2,
 array([1., 1., 0.]))

In [ ]:
#Cộng ma trận
np.add(A, D)

matrix([[4.08768658, 3.85389179],
        [2.17440832, 6.89708995]])

In [ ]:
#Trừ ma trận
np.subtract(A, D)

matrix([[-3.91231342, -2.14610821],
        [-1.82559168, -5.10291005]])

In [ ]:
#Chia ma trận
np.divide(A, D)

matrix([[0.02192164, 0.2846306 ],
        [0.08720416, 0.14951499]])

In [ ]:
#Nhân ma trận
A @ D #Phiên bản Py 3.x
np.multiply(D, A)
np.dot(D, A)

matrix([[0.87397126, 6.10683699],
        [1.22182306, 7.09032325]])

In [ ]:
#Hàm lũy thừa ma trận
linalg.expm(A)
#Hàm logarith ma trận
linalg.logm(A)

array([[-2.32507026+2.70759747j,  2.10426564-2.39856961j],
       [ 0.42979853-0.48991043j, -0.33043847+0.43399519j]])

# **Câu 2**

In [ ]:
import numpy as np
#Tính ma trận A
A = np.array([ [0,1], [1,0]])
print(A)
temp = A.dot(A) # tính toan lần thứ 1
print(temp)
k = 6
for i in range(k-1):
  temp = temp.dot(A)
print (temp)
print('---')
#Tính ma trận B
B = np.array([ [0,-1], [-1,0]])
print(B)
temp = B.dot(B) # tính toan lần thứ 1
print(temp)
k= 5
for i in range(k-1):
  temp = temp.dot(B)
print (temp)
print('---')
#Ma trận hội tụ
C = np.array([ [1, 0, 0], [0, 0.5, 1], [0, 0, 0.5] ])
print(C)
temp = C.dot(C) # tính toan lần thứ 1
print(temp)
k= 1000
for i in range(k-1):
  temp = temp.dot(C)
print(temp)
k= 1000
for i in range(k-1):
  temp = temp.dot(C)
print(temp)

[[0 1]
 [1 0]]
[[1 0]
 [0 1]]
[[0 1]
 [1 0]]
---
[[ 0 -1]
 [-1  0]]
[[1 0]
 [0 1]]
[[1 0]
 [0 1]]
---
[[1.  0.  0. ]
 [0.  0.5 1. ]
 [0.  0.  0.5]]
[[1.   0.   0.  ]
 [0.   0.25 1.  ]
 [0.   0.   0.25]]
[[1.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 4.66631809e-302 9.34196882e-299]
 [0.00000000e+000 0.00000000e+000 4.66631809e-302]]
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#Ma trận Markov
M = np.array([ [0.8, 0.3], [0.2, 0.7]])
MM = M.dot(M) # tính M2, nghĩa là M2
print (MM)
MMM = M.dot(MM) # tính M3
print (MMM)
for i in range(100): # tính các M^ khác.
  MM = MM.dot(M)
print (MM) # kết luận xu hướng của M mũ vô hạn

[[0.7  0.45]
 [0.3  0.55]]
[[0.65  0.525]
 [0.35  0.475]]
[[0.6 0.6]
 [0.4 0.4]]


# **Câu 3**

In [ ]:
#Phân rã ma trận LU
M = np.array([ [0.8, 0.3], [0.2, 0.7]])
P, L, U = linalg.lu(M) # lệnh lina.lu sẽ tách ma trận M thành 3 ma trận P, L và U
print (P)
print (L)
print (U)
L.dot(U)

[[1. 0.]
 [0. 1.]]
[[1.   0.  ]
 [0.25 1.  ]]
[[0.8   0.3  ]
 [0.    0.625]]


array([[0.8, 0.3],
       [0.2, 0.7]])

# **Câu 5**

In [ ]:
#Bài toán loan tin
A = np.array([ [0,1,0,1],[0,0,1,0],[1,0,0,1],[1,1,0,0]])
temp = A.dot(A) # lúc này temp =› A^2
print(temp)
temp = temp.dot(A) # lúc này temp =› A^3
print(temp)

[[1 1 1 0]
 [1 0 0 1]
 [1 2 0 1]
 [0 1 1 1]]
[[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]


In [ ]:
A = np.array([ [0,1,0,1],[0,0,1,0],[1,0,0,1],[1,1,0,0]])
sumA = A
temp = A.dot(A)
k = 3
sumA = sumA + temp
for i in range(1, k-1):
  temp = temp.dot(A)
sumA = sumA + temp
print (temp)
print('---')
print (sumA)

[[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]
---
[[2 3 2 3]
 [2 2 1 2]
 [3 4 2 3]
 [3 3 2 2]]


# **Bài tập chương 3**

Câu 1

In [1]:
import numpy as np

def la_ma_tran_kha_nghich(ma_tran):
    try:
        np.linalg.inv(ma_tran)
        return True
    except np.linalg.LinAlgError:
        return False

def chuoi_thanh_ma_tran(chuoi):
    ma_ascii = [ord(ky_tu) for ky_tu in chuoi]
    while len(ma_ascii) % 3 != 0:
        ma_ascii.append(0)
    return np.array(ma_ascii).reshape(-1, 3)

def ma_tran_thanh_chuoi(ma_tran):
    ky_tu = [chr(int(round(so))) for dong in ma_tran for so in dong if int(round(so)) != 0]
    return ''.join(ky_tu)

def main():
    print("=== CHƯƠNG TRÌNH MÃ HÓA & GIẢI MÃ SỬ DỤNG MA TRẬN 3x3 ===\n")

    # a. Tự chọn một ma trận khả nghịch
    ma_tran_khoa = np.array([[2, -1, 0],[1, 1, 1],[0, -1, 2] ])
    print(f" Ma trận khóa được chọn:\n{ma_tran_khoa}\n")

    if la_ma_tran_kha_nghich(ma_tran_khoa):
        print(" Ma trận khả nghịch (có thể giải mã)\n")
    else:
        print(" Ma trận không khả nghịch")
        return

    # b. Nhập họ tên hoặc mã số sinh viên
    chuoi_goc = input("Nhập họ tên hoặc mã số sinh viên: ")

    # c. Mã hóa
    ma_tran_du_lieu = chuoi_thanh_ma_tran(chuoi_goc)
    print(f"\n Ma trận ASCII từ chuỗi:\n{ma_tran_du_lieu}")

    ma_tran_ma_hoa = ma_tran_du_lieu @ ma_tran_khoa
    print(f"\n Kết quả mã hóa:\n{ma_tran_ma_hoa}")

    # d. Giải mã
    ma_tran_khoa_nghich = np.linalg.inv(ma_tran_khoa)
    ma_tran_giai_ma = ma_tran_ma_hoa @ ma_tran_khoa_nghich
    print(f"\n Ma trận sau giải mã:\n{ma_tran_giai_ma}")

    chuoi_khoi_phuc = ma_tran_thanh_chuoi(ma_tran_giai_ma)
    print(f"\n Chuỗi sau khi giải mã: {chuoi_khoi_phuc}")
if __name__ == "__main__":
    main()

=== CHƯƠNG TRÌNH MÃ HÓA & GIẢI MÃ SỬ DỤNG MA TRẬN 3x3 ===

 Ma trận khóa được chọn:
[[ 2 -1  0]
 [ 1  1  1]
 [ 0 -1  2]]

 Ma trận khả nghịch (có thể giải mã)

Nhập họ tên hoặc mã số sinh viên: Phạm Minh Huy

 Ma trận ASCII từ chuỗi:
[[ 80 104  97]
 [803 109  32]
 [ 77 105 110]
 [104  32  72]
 [117 121   0]]

 Kết quả mã hóa:
[[ 264  -73  298]
 [1715 -726  173]
 [ 259  -82  325]
 [ 240 -144  176]
 [ 355    4  121]]

 Ma trận sau giải mã:
[[ 80. 104.  97.]
 [803. 109.  32.]
 [ 77. 105. 110.]
 [104.  32.  72.]
 [117. 121.   0.]]

 Chuỗi sau khi giải mã: Phạm Minh Huy


Câu 2

In [2]:
import numpy as np

def tinh_p_q(ds_c):
    """Tính p_n và q_n từ danh sách [c0, c1, ..., cn]"""
    p_prev, p = 1, ds_c[0]
    q_prev, q = 0, 1

    for i in range(1, len(ds_c)):
        p_next = ds_c[i] * p + p_prev
        q_next = ds_c[i] * q + q_prev
        p_prev, p = p, p_next
        q_prev, q = q, q_next

    return p, q

def kiem_tra_ma_tran(ds_c):
    """Tính tích các ma trận theo công thức"""
    ket_qua = np.identity(2, dtype=int)

    for c in ds_c:
        A = np.array([[c, 1], [1, 0]])
        ket_qua = np.dot(ket_qua, A)

    vec = np.array([[1], [0]])
    p_q = np.dot(ket_qua, vec)
    return p_q.flatten()

ds_8_3 = [2, 1, 2]
ds_11_3 = [3, 1, 2]

print("Phân số 8/3:")
p, q = tinh_p_q(ds_8_3)
print(f"  a. Kết quả tính p_n, q_n = {p}, {q}  {p}/{q}")
ma_tran_ket_qua = kiem_tra_ma_tran(ds_8_3)
print(f"  b. Kiểm tra bằng công thức ma trận: p_n = {ma_tran_ket_qua[0]}, q_n = {ma_tran_ket_qua[1]}")

print("\n Phân số 11/3:")
p, q = tinh_p_q(ds_11_3)
print(f"  a. Kết quả tính p_n, q_n = {p}, {q} {p}/{q}")
ma_tran_ket_qua = kiem_tra_ma_tran(ds_11_3)
print(f"  b. Kiểm tra bằng công thức ma trận: p_n = {ma_tran_ket_qua[0]}, q_n = {ma_tran_ket_qua[1]}")

Phân số 8/3:
  a. Kết quả tính p_n, q_n = 8, 3  8/3
  b. Kiểm tra bằng công thức ma trận: p_n = 8, q_n = 3

 Phân số 11/3:
  a. Kết quả tính p_n, q_n = 11, 3 11/3
  b. Kiểm tra bằng công thức ma trận: p_n = 11, q_n = 3
