In [1]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
tich = np.inner(a,b)
print (tich)

32


In [2]:
np.dot(a,b)

np.int64(32)

In [3]:
import numpy as np
a = np.array([1,2,-3])
np.linalg.norm(a)
np.linalg.norm(a, 2)


np.float64(3.7416573867739413)

In [4]:
a = np.array([1,2,-3])
np.linalg.norm(a,1)

np.float64(6.0)

In [5]:
def chuan(v,k):
 tong = 0
 for i in range(len(v)):
  tong = tong + abs(v[i]**k)
 ketqua = math.pow(tong, 1.0/k)
 return ketqua

In [6]:
import math
import numpy as np
a = np.array([1,2,-3])
chuan(a, 1)

6.0

In [7]:
np.linalg.norm(a,1)

np.float64(6.0)

In [8]:
chuan(a, 2)

3.7416573867739413

In [9]:
np.linalg.norm(a,2)

np.float64(3.7416573867739413)

In [10]:
chuan(a, 3)

3.3019272488946263

In [11]:
np.linalg.norm(a,3)

np.float64(3.3019272488946263)

In [12]:
chuan(a, 1000)

1.0442214818467515

In [16]:
np.linalg.norm(a,1000)

/usr/local/lib/python3.11/dist-packages/numpy/linalg/_linalg.py:2780: RuntimeWarning: overflow encountered in power
  absx **= ord


np.float64(inf)

In [15]:
from scipy import linalg
linalg.norm(a)

np.float64(3.7416573867739413)

In [17]:
linalg.norm(a, 100)

np.float64(3.0)

In [18]:
linalg.norm(a, 1000)

/usr/local/lib/python3.11/dist-packages/numpy/linalg/_linalg.py:2780: RuntimeWarning: overflow encountered in power
  absx **= ord


np.float64(inf)

In [19]:
import numpy as np
m = 10
v1 = np.array([5,-4,3])
v2 = np.array([4,3,-2])
v3 = np.array([-4,-3,-1])
v4 = np.array([-9,8,6])
mi = np.array([2,5,2,1])
M = np.array([v1,v2,v3,v4])
MT = M.transpose()
MT

array([[ 5,  4, -4, -9],
       [-4,  3, -3,  8],
       [ 3, -2, -1,  6]])

In [20]:
v = (1.0/m)*MT.dot(mi)
print (v)

[1.3 0.9 0. ]


In [21]:
import sympy as sym
x, y = sym.symbols('x y')
xy = sym.Matrix([x,y])
A = sym.Matrix([[1, -68],[1,1]])
v = sym.Matrix([0, 1])
nghiem = sym.solve([A*xy-v])
print(sym.pretty(nghiem))

⎧   68         ⎫
⎨x: ──, y: 1/69⎬
⎩   69         ⎭


In [22]:
import sympy
x, y, Lambda = sympy.symbols('x y Lambda')
I = sympy.eye(2)

In [23]:
A = sympy.Matrix([[2,3],[3,-6]])
phuongtrinh = sympy.Eq(sympy.det(Lambda*I-A), 0)
nghiem = sympy.solve(phuongtrinh)
print([sympy.N(phantu,4) for phantu in nghiem])

[-7.000, 3.000]


In [24]:
import sympy
x, y, Lambda = sympy.symbols('x y Lambda')
I = sympy.eye(2)

In [25]:
A = sympy.Matrix([[2,3],[3,-6]])
phuongtrinh = sympy.Eq(sympy.det(Lambda*I-A), 0)
nghiem = sympy.solve(phuongtrinh)
print([sympy.N(phantu,4) for phantu in nghiem])

[-7.000, 3.000]


In [26]:
print (sympy.pretty(nghiem))

[-7, 3]


In [27]:
import numpy as np
A = np.array([[2,3],[3,-6]])
D = np.array([[-7,0],[0,3]])
P = np.array([[-1.0/3, 3],[1,1]])
from numpy import linalg
from numpy import linalg as LA
P1 = LA.inv(P)
print (P1)

[[-0.3  0.9]
 [ 0.3  0.1]]


In [28]:
A.dot(P)

array([[ 2.33333333,  9.        ],
       [-7.        ,  3.        ]])

In [29]:
P.dot(D)

array([[ 2.33333333,  9.        ],
       [-7.        ,  3.        ]])

In [30]:
P @ (D ** 1000) @ P1

array([[ 5.03503397e+18,  3.50482117e+18],
       [ 3.50482117e+18, -4.31115581e+18]])

In [31]:
print (D **2)

[[49  0]
 [ 0  9]]


In [32]:
import numpy as np
a = np.array([1,2,3])
mag = np.sqrt(a.dot(a))
mag = np.sqrt(a @ a )
mag = np.sqrt(np.inner(a,a))
mag = lambda x : math.sqrt(sum(i** 2 for i in x))
mag(a)

3.7416573867739413

In [34]:
import numpy as np
import math

a = np.array([1, 2, 3])

# Câu a
mag_a = np.sqrt(a.dot(a))

# Câu b
mag_b = np.sqrt(a @ a)

# Câu c
mag_c = np.sqrt(np.inner(a, a))

# Câu d
mag_d_func = lambda x: math.sqrt(sum(i**2 for i in x))
mag_d = mag_d_func(a)

# In kết quả
print("Câu a:", mag_a)
print("Câu b:", mag_b)
print("Câu c:", mag_c)
print("Câu d:", mag_d)
print('Tất cả các câu a, b, c, d đều đúng và đều tính chuẩn 2 của vector a.')

Câu a: 3.7416573867739413
Câu b: 3.7416573867739413
Câu c: 3.7416573867739413
Câu d: 3.7416573867739413
Tất cả các câu a, b, c, d đều đúng và đều tính chuẩn 2 của vector a.


In [35]:
import numpy as np
from math import acos, degrees

# Nhập vector u và v
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])

# a. Tính khoảng cách giữa 2 vector: ||u - v||
def vector_distance(u, v):
    return np.linalg.norm(u - v)

# b. Tính góc θ giữa 2 vector u và v (tính bằng độ)
def angle_between_vectors(u, v):
    dot_product = np.dot(u, v)
    norm_u = np.linalg.norm(u)
    norm_v = np.linalg.norm(v)
    cos_theta = dot_product / (norm_u * norm_v)
    angle_rad = acos(cos_theta)
    angle_deg = degrees(angle_rad)
    return angle_deg

# c. Phép chiếu trực giao p của u lên v
def orthogonal_projection(u, v):
    projection_scalar = np.dot(u, v) / np.dot(v, v)
    projection = projection_scalar * v
    return projection

print("a) ||u - v|| =", vector_distance(u, v))
print("b) Góc giữa u và v (độ) =", angle_between_vectors(u, v))
print("c) Phép chiếu trực giao p của u lên v =", orthogonal_projection(u, v))


a) ||u - v|| = 5.196152422706632
b) Góc giữa u và v (độ) = 12.933154491899135
c) Phép chiếu trực giao p của u lên v = [1.66233766 2.07792208 2.49350649]
